// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetPlugin(arg1:string):Promise<wails.PluginDto>;

export function GetPluginHistory(arg1:string):Promise<Array<wails.PluginHistoryEntryDto>>;

export function GetPlugins():Promise<Array<wails.PluginSummaryDto>>;

export function ReloadPlugins():Promise<wails.ReloadPluginsResponse>;

export function SavePluginHistory(arg1:string,arg2:Record<string, any>):Promise<void>;

export function ValidateFormData(arg1:string,arg2:Record<string, any>):Promise<wails.ValidationResultDto>;
