// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlugin(arg1) {
  return window['go']['wails']['PluginApi']['GetPlugin'](arg1);
}

export function GetPluginHistory(arg1) {
  return window['go']['wails']['PluginApi']['GetPluginHistory'](arg1);
}

export function GetPlugins() {
  return window['go']['wails']['PluginApi']['GetPlugins']();
}

export function ReloadPlugins() {
  return window['go']['wails']['PluginApi']['ReloadPlugins']();
}

export function SavePluginHistory(arg1, arg2) {
  return window['go']['wails']['PluginApi']['SavePluginHistory'](arg1, arg2);
}

export function ValidateFormData(arg1, arg2) {
  return window['go']['wails']['PluginApi']['ValidateFormData'](arg1, arg2);
}
