// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['wails']['SettingsApi']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['wails']['SettingsApi']['SaveSettings'](arg1);
}
