// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';
import {context} from '../models';

export function GetSystemInfo():Promise<wails.SystemInfoDto>;

export function OpenFileDialog(arg1:string,arg2:Array<wails.FileFilterDto>):Promise<wails.DialogResponse>;

export function OpenFolderDialog(arg1:string):Promise<wails.DialogResponse>;

export function SaveFileDialog(arg1:string,arg2:Array<wails.FileFilterDto>):Promise<wails.DialogResponse>;

export function SetContext(arg1:context.Context):Promise<void>;
