// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemInfo() {
  return window['go']['wails']['SystemApi']['GetSystemInfo']();
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['wails']['SystemApi']['OpenFileDialog'](arg1, arg2);
}

export function OpenFolderDialog(arg1) {
  return window['go']['wails']['SystemApi']['OpenFolderDialog'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['wails']['SystemApi']['SaveFileDialog'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['wails']['SystemApi']['SetContext'](arg1);
}
