// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CancelTask(arg1:string):Promise<wails.CancelTaskResponse>;

export function DeleteTask(arg1:string):Promise<wails.DeleteTaskResponse>;

export function GetTask(arg1:string):Promise<wails.TaskDto>;

export function GetTaskOutput(arg1:string):Promise<Array<wails.OutputEventDto>>;

export function GetTasks():Promise<Array<wails.TaskDto>>;

export function RunPlugin(arg1:wails.RunPluginRequest):Promise<wails.RunPluginResponse>;
