// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask(arg1) {
  return window['go']['wails']['TaskApi']['CancelTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['wails']['TaskApi']['DeleteTask'](arg1);
}

export function GetTask(arg1) {
  return window['go']['wails']['TaskApi']['GetTask'](arg1);
}

export function GetTaskOutput(arg1) {
  return window['go']['wails']['TaskApi']['GetTaskOutput'](arg1);
}

export function GetTasks() {
  return window['go']['wails']['TaskApi']['GetTasks']();
}

export function RunPlugin(arg1) {
  return window['go']['wails']['TaskApi']['RunPlugin'](arg1);
}
